Fix/cd deploy (#59)
* remove nvm config

* Update cd.yml

* use vars for APP_DIR

* Update cd.yml

* use PAT to clone

* Update cd.yml

* Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -21,22 +21,22 @@ jobs:
             set -e
 
             echo "=== Load environment ==="
-            export HOME=/home/dev
-            export NVM_DIR="$HOME/.nvm"
+            # export HOME=/home/dev
+            # export NVM_DIR="$HOME/.nvm"
 
-            if [ -s "$NVM_DIR/nvm.sh" ]; then
-              . "$NVM_DIR/nvm.sh"
-              nvm use 24
-            else
-              echo "NVM not found"
-              exit 1
-            fi
+            # if [ -s "$NVM_DIR/nvm.sh" ]; then
+            #   . "$NVM_DIR/nvm.sh"
+            #   nvm use 24
+            # else
+            #   echo "NVM not found"
+            #   exit 1
+            # fi
 
-            export PATH="$NVM_DIR/versions/node/v24.12.0/bin:/usr/local/bin:/usr/bin:$PATH"
+            # export PATH="$NVM_DIR/versions/node/v24.12.0/bin:/usr/local/bin:/usr/bin:$PATH"
 
             echo "Ensure app directory exists"
-            mkdir -p ${{ secrets.APP_DIR }}
-            cd ${{ secrets.APP_DIR }}
+            mkdir -p ${{ vars.APP_DIR }}
+            cd ${{ vars.APP_DIR }}
 
             echo "Prepare rollback directories"
             rm -rf failed || true
@@ -48,7 +48,7 @@ jobs:
             fi
 
             echo "Clone new version"
-            git clone https://github.com/osdrm-dev/api-backend.git current || {
+            git clone https://${{secrets.GH_ACCESS_TOKEN}}@github.com/osdrm-dev/api-backend.git current || {
               echo "Git clone failed, rollback"
               rm -rf current
               mv previous current
