OSDRM-16 updates the cd.yml for making our npm to access its version in server

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -21,6 +21,20 @@ jobs:
           script: |
             set -e
 
+            echo "=== Load environment ==="
+            export HOME=/home/dev
+            export NVM_DIR="$HOME/.nvm"
+
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+              nvm use 24
+            else
+              echo "NVM not found"
+              exit 1
+            fi
+
+            export PATH="$NVM_DIR/versions/node/v24.12.0/bin:/usr/local/bin:/usr/bin:$PATH"
+
             echo "Ensure app directory exists"
             mkdir -p ${{ secrets.APP_DIR }}
             cd ${{ secrets.APP_DIR }}
